[features]
seeds = false
skip-lint = false

[programs.localnet]
sentry = "EPccz8vhrRpLK6w4WwPQn5aMC2Hh6onsD24qmtUVK1sm"

[programs.devnet]
sentry = "EPccz8vhrRpLK6w4WwPQn5aMC2Hh6onsD24qmtUVK1sm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/sentry-dev.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
setup = "node dist/scripts/setup.js"
bot = "node dist/scripts/sentinel-bot.js"
live = "node dist/scripts/sentinel-realtime.js"
